### PR TITLE
Support SharedAccessSignature

### PR DESCRIPTION
**Pull request by ened**
Adds support for SharedAccessSignature; which is used for clients that do not have access to the full account key.

Also did some code formatting - my default setting in in the IDE. Apologies if this causes review trouble.

### CODE REVIEW

**Comment by Algure** [comment]
Much thanks. Would review.

**Comment by ened** [comment]
@Algure do you have questions on this PR?

**Comment by Algure** [comment]
Yes please. It seems that formatting you spoke of really did the thing you said it would. Could you please specify the functions you modified so I know what to look at.

Much thanks.

**Comment by ened** [comment]
Please look at https://github.com/Algure/azstore/pull/4/files#diff-1d32b6a1bb6b35b6994121a7b914bd032f49cf78a73d0b84175f17652d259a58L95 for support of parsing SharedAccessSignature from the connections string, then https://github.com/Algure/azstore/pull/4/files#diff-1d32b6a1bb6b35b6994121a7b914bd032f49cf78a73d0b84175f17652d259a58L117 for the change in the uri function. This will simply put the shared access signature into the query.

https://github.com/Algure/azstore/pull/4/files#diff-1d32b6a1bb6b35b6994121a7b914bd032f49cf78a73d0b84175f17652d259a58R200 shows how accountKey is now optional, it used to be required. 

Perhaps some unit tests would be more helpful here.

**Comment by Algure** [comment]
Awesome ! Your PR has been merged and would be part of the next release rolling out in a few weeks. Further tests would be done on my end before then to properly update the docs.

Much thanks.

**Comment by ened** [comment]
Hi Algure, I found a bug in the current MR, will send another MR.

**Pull request merged**
