### PR TITLE
ensure to only specify query or queryParameters

### PR DESCRIPTION
**Pull request by ened**

### CODE REVIEW

**Comment by ened** [comment]
@Algure please take another look

**Comment by Algure** [comment]
It's all in the schedule @ened , Would take a look and write my tests like I said.

Much thanks.

**Comment by ened** [comment]
@Algure please take a look at the "Files changed (3)" tab on the top right for details.

Screenshot 2021-06-22 at 09 29 21

**Comment by ened** [comment]
Hi @Algure just a reminder to review this one. :)

**Pull request merged**
